name: Deploy to Nekoweb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare build
        run: |
          mkdir -p ./_site
          cp -r ./public/* ./_site

      - name: Deploy to Nekoweb
        uses: mp-pinheiro/nekoweb-deploy@main
        with:
          API_KEY: ${{ secrets.NEKOWEB_API_KEY }}
          BUILD_DIR: "./_site"
          DEPLOY_DIR: "/test"
          CLEANUP: "False"
          DELAY: "0.5"
          NEKOWEB_PAGENAME: "trademark"

      - name: Update build date on index
        run: |
          BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          sed -i "s/<meta name=\"build-date\" content=\"[^\"]*\"/<meta name=\"build-date\" content=\"$BUILD_DATE\"/" ./test/index.html
          cat ./_site/index.html
        env:
          API_KEY: ${{ secrets.NEKOWEB_API_KEY }}